### ISSUE TITLE
API Lab Coding

### ISSUE THREAD

**Issue by Volatar** [Volatar/Group7-repo-projects#48]

**Comment by dlingle1** [comment]
I added login and sign-up functionality to the API branch for the web-app.  There are issues with the login at the moment and I will need to further expand the web-app to access pages better.

**Comment by dlingle1** [comment]
aef07076927f83a753583fa27c275c3827cc39ae I reverted back to the initial repo of the branch in order to start fresh on API.

74967c2c7b166e76920c864ee1ae9a6b9f628f25 I committed an initial API.  I was having trouble testing it with the Python request library, which took some time to resolve.  Put and Get should be working now.

**Comment by dlingle1** [comment]
5ea19bd899cefe1207b83fbad1c8e68e6a65dc29 I expanded API methods to include post and delete.  I also provided some basic error-catching to prevent non-descriptive crashing.  I further expanded the testing program of the python request library as well.
